### ISSUE TITLE
Self Hosted - Cloudformation - [Makefile:27: deploy-cloudwan-active] Error 255

### ISSUE THREAD

**Issue by nterthevoid** [aws-samples/aws-cloudwan-workshop-code#1]
Fails with error when using make deploy.     

From Stackset status
The following resource(s) failed to update: [CoreNetwork].

1 validation error detected: Value 'Incorrect policy. (Service: NetworkManager, Status Code: 400, Request ID: a7b53b81-3ffe-4888-b02a-e132513ef8a3): [{ErrorCode: MAXIMUM_ITEMS_EXCEEDED, Message: $.segment-actions[1].destinations: blackhole may only exist in a singleton list}, {ErrorCode: INVALID_STRING, Message: $.segment-actions[1].destinations[0]: attachment identifiers must be prefixed with "attachment-" and must end in 17 characters where all characters are from the set "a..f" or "0..9"}, {ErrorCode: CONSTANT_VIOLATION, Message: $.segment-actions[1].destinations[0]: must be a constant value blackhole}, {ErrorCode: INVALID_STRING, Message: $.segment-actions[1].destinations[1]: attachment identifiers must be prefixed with "attachment-" and must end in 17 characters where all characters are from the set "a..f" or "0..9"}, {ErrorCode: CONSTANT_VIOLATION, Message: $.segment-actions[1].destinations[1]: must be a constant value blackhole}, {ErrorCode: REQUIRED_PROPERTY, Message: $.segment-actions[1].mode: is missing but it is required}, {ErrorCode: REQUIRED_PROPERTY, Message: $.segment-actions[1].share-with: is missing but it is required}, {ErrorCode: MAXIMUM_ITEMS_EXCEEDED, Message: $.segment-actions[2].destinations: blackhole may only exist in a singleton list}, {ErrorCode: INVALID_STRING, Message: $.segment-actions[2].destinations[0]: attachment identifiers must be prefixed with "attachment-" and must end in 17 characters where all characters are from the set "a..f" or "0..9"}, {ErrorCode: CONSTANT_VIOLATION, Message: $.segment-actions[2].destinations[0]: must be a constant value blackhole}, {ErrorCode: INVALID_STRING, Message: $.segment-actions[2].destinations[1]: attachment identifiers must be prefixed with "attachment-" and must end in 17 characters where all characters are from the set "a..f" or "0..9"}, {ErrorCode: CONSTANT_VIOLATION, Message: $.segment-actions[2].destinations[1]: must be a constant value blackhole}, {ErrorCode: REQUIRED_PROPERTY, Message: $.segment-actions[2].mode: is missing but it is required}, {ErrorCode: REQUIRED_PROPERTY, Message: $.segment-actions[2].share-with: is missing but it is required}]' at 'statusMessage' failed to satisfy constraint: Member must have length less than or equal to 1024

**Comment by pablo19sc** [comment]
Updated the CloudFormation code with the udpate of the Cloud WAN Workshop (added TGW - CloudWAN peering, plus minor changes in the original code). Tested with new version and everything should be fixed now.

Check the README, as now we implemented a new way to deploy the resources.
