### ISSUE TITLE
issue with terraform\modules\compute\main.tf

### ISSUE THREAD

**Issue by teholm** [aws-samples/aws-cloudwan-workshop-code#11]
line # 46 needs to be updated to: "amzn2-ami-hvm-*-gp2" or it will fail to find the most current AMI.

**Comment by pablo19sc** [comment]
Hi! Let me work in the updates during today and tomorrow

**Comment by pablo19sc** [comment]
Hi @teholm. Fixed issue - now we are using Amazon Linux 2023 AMI
