### ISSUE TITLE
Readme.md file points to Cloud WAN Workshop that doesn't exist anymore.

### ISSUE THREAD

**Issue by teholm** [aws-samples/aws-cloudwan-workshop-code#12]
The readme.md file points to the Cloud WAN workshop (https://catalog.workshops.aws/cloudwan/en-US) but that page does not exist.

This is the paragraph:
_This repository shows you an example of global communication with AWS Cloud WAN, showing the same architecture you can build in the [AWS Cloud WAN Workshop](https://catalog.workshops.aws/cloudwan/en-US) using different Infrastructure as Code (IaC) frameworks: CloudFormation, CDK (with Typescript and Python examples) and Terraform._

**Comment by SonyDavid** [comment]
I was really excited about this till I ran into the same thing.

**Comment by pablo19sc** [comment]
Hi! We have published again the workshop, so the link exists again :)
