### ISSUE TITLE
Terraform fails with   │ Error: AWS SDK Go Service Operation Incomplete

### ISSUE THREAD

**Issue by nterthevoid** [aws-samples/aws-cloudwan-workshop-code#2]
│   with module.nvirginia_spoke_vpcs["prod"].awscc_ec2_subnet_route_table_association.cwan["us-east-1a"],
│   on .terraform/modules/nvirginia_spoke_vpcs/main.tf line 333, in resource "awscc_ec2_subnet_route_table_association" "cwan":
│  333: resource "awscc_ec2_subnet_route_table_association" "cwan" {
│ 
│ Waiting for Cloud Control API service CreateResource operation completion returned: waiter state transitioned to FAILED. StatusMessage: The subnet ID 'subnet-0751c60afa92b52d5' does not exist (Service: Ec2, Status Code: 400,
│ Request ID: 5524c626-b6ba-4a98-b60a-44cd62764121). ErrorCode: GeneralServiceException

**Comment by pablo19sc** [comment]
Hi! we have updated the Terraform code with the new version of the workshop. I tested everything and it's working without errors. Can you please check?
